services:
  # --- Backend API Service ---
  api:
    build: ./server
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
  
  # --- PostgreSQL Database Service ---
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  # --- API Documentation Service ---
  docs:
    image: swaggerapi/swagger-ui:v5.17.14
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      URL: /webudget_api_spec_v1.yaml
    volumes:
      - ./server/webudget_api_spec_v1.yaml:/usr/share/nginx/html/webudget_api_spec_v1.yaml

# --- Volumes Definition ---
volumes:
  postgres_data: