services:
  # --- Backend API Service ---
  api:
    build: ./server
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - db

  migrate:
    build:
      context: ./server
    image: webudget-api # Use the same image as the api service
    depends_on:
      - db # Ensure the database is ready before trying to run migrations
    env_file:
      - .env
    command: ["npm", "run", "migrate:up"]
  
  # --- PostgreSQL Database Service ---
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  # --- API Documentation Service ---
  docs:
    image: swaggerapi/swagger-ui:v5.17.14
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    environment:
      URL: /webudget_api_spec_v1.yaml
    volumes:
      - ./server/webudget_api_spec_v1.yaml:/usr/share/nginx/html/webudget_api_spec_v1.yaml

# --- Volumes Definition ---
volumes:
  postgres_data: