# WeBudget API Specification v1.1.0
# This document defines the RESTful API for the WeBudget MVP.
# It follows the OpenAPI 3.0 standard.

openapi: 3.0.3
info:
  title: "WeBudget API"
  description: |-
    The official API specification for the WeBudget personal finance management application.
    This API is used by all WeBudget clients (Web, iOS, Android) to interact with user financial data.

    Core Principles:
    - **Versioning:** URL Path Versioning (/api/v1)
    - **Authentication:** JWT via HttpOnly Cookie (and Authorization header for non-web clients)
    - **Data Format:** JSON with camelCase keys
    - **Dates:** ISO 8601 format (YYYY-MM-DDTHH:mm:ss.sssZ)
    - **Error Handling:** Standardized JSON error body
    - **Pagination:** Offset/Limit strategy
  version: "1.1.0"
  contact:
    name: "Backend Team"
    email: "etiennebeaulac@gmail.com"

servers:
  - url: http://localhost:3000/api/v1
    description: Local development server
  - url: https://api.webudget.app/api/v1
    description: Production server (Future)

security:
  - bearerAuth: []

tags:
  - name: Plaid
    description: Endpoints for integrating with the Plaid API.
  - name: Institutions
    description: Endpoints for managing and retrieving linked financial institutions.
  - name: Transactions
    description: Endpoints for retrieving transactions.
  - name: Health
    description: Application health check.

# ===============================================================================
# PATHS - The core endpoint definitions for the API.
# ===============================================================================
paths:
  # --- Plaid Integration ---
  /plaid/create-link-token:
    post:
      tags:
        - Plaid
      summary: Create Plaid Link Token
      description: |-
        Generates a short-lived `link_token` required to initialize the Plaid Link frontend component.
      operationId: createLinkToken
      responses:
        "200":
          description: Successfully created the link token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  linkToken:
                    type: string
                    example: "link-sandbox-c8b1b0a7-a37e-405a-8b89-9b993302758f"
                  expiration:
                    type: string
                    format: date-time
                    example: "2025-06-17T20:34:25.000Z"
        "401":
          $ref: '#/components/responses/Unauthorized'
        "429":
          $ref: '#/components/responses/TooManyRequests'
        "500":
          $ref: '#/components/responses/InternalServerError'

  /plaid/exchange-public-token:
    post:
      tags:
        - Plaid
      summary: Exchange Public Token
      description: |-
        Exchanges a `public_token` for a permanent `access_token` and creates a new Institution resource.
        This endpoint queues a background job for the initial data sync and immediately returns a `202 Accepted`.
      operationId: exchangePublicToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - publicToken
              properties:
                publicToken:
                  type: string
                  description: The public token from the Plaid Link success callback.
      responses:
        "202":
          description: |-
            Accepted. The token exchange was successful and the initial data sync has been queued.
            The response body contains the newly created Institution resource with a `syncStatus` of `syncing`.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaidItem'
        "400":
          $ref: '#/components/responses/BadRequest'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "500":
          $ref: '#/components/responses/InternalServerError'

  # --- Institutions ---
  /institutions:
    get:
      tags:
        - Institutions
      summary: Get All Institutions and their Accounts
      description: |-
        Returns a list of all financial institutions for the authenticated user, with their nested accounts.
      operationId: getInstitutions
      responses:
        "200":
          description: A list of the user's institutions, each containing their accounts.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/PlaidItemWithAccounts'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "500":
          $ref: '#/components/responses/InternalServerError'

  /institutions/{institutionId}:
    delete:
      tags:
        - Institutions
      summary: Archive Linked Institution
      description: |-
        Archives a connection to a financial institution. This performs a soft delete.
        All associated accounts and transactions will be hidden from the user but preserved in the system.
      operationId: deleteInstitution
      parameters:
        - $ref: '#/components/parameters/InstitutionId'
      responses:
        "200":
          description: The institution was successfully archived. The response body contains the updated resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaidItem'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalServerError'

  /institutions/{institutionId}/refresh:
    post:
      tags:
        - Institutions
      summary: Trigger Manual Data Refresh
      description: |-
        Triggers an immediate, asynchronous data refresh for a specific institution.
        The API will respond with `202 Accepted` and queue a background job to sync transactions.
      operationId: refreshInstitution
      parameters:
        - $ref: '#/components/parameters/InstitutionId'
      responses:
        "202":
          description: |-
            Accepted. The data refresh has been successfully queued.
            The response body contains the institution resource with its `syncStatus` updated to `syncing`.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaidItem'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFound'
        "429":
          $ref: '#/components/responses/TooManyRequests'
        "500":
          $ref: '#/components/responses/InternalServerError'

  # --- Transactions ---
  /transactions:
    get:
      tags:
        - Transactions
      summary: List All Transactions
      description: |-
        Returns a paginated list of all transactions for the authenticated user from all linked accounts.
        Supports filtering by date range, account, and search query.
      operationId: getTransactions
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 25
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
        - name: accountId
          in: query
          schema:
            type: string
        - name: startDate
          in: query
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          schema:
            type: string
            format: date
        - name: category
          in: query
          schema:
            type: string
        - name: searchText
          in: query
          schema:
            type: string
      responses:
        "200":
          description: A paginated list of transactions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagination:
                    $ref: '#/components/schemas/Pagination'
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
        "400":
          $ref: '#/components/responses/BadRequest'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "500":
          $ref: '#/components/responses/InternalServerError'

  # --- Health Check ---
  /health:
    get:
      tags:
        - Health
      summary: System Health Check
      operationId: getHealth
      description: |-
        A public, unauthenticated endpoint to verify that the API service is running and can connect to its dependencies.
        Returns the operational status of the service.
      security: []
      responses:
        "200":
          description: The service is healthy.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "OK"
                  timestamp:
                    type: string
                    format: date-time

# ===============================================================================
# COMPONENTS - Reusable schemas, parameters, and responses.
# ===============================================================================
components:
  # --- Schemas (Data Models) ---
  schemas:
    PlaidItem:
      type: object
      properties:
        id:
          type: string
          description: The unique ID for the Institution in our database.
          example: "inst_11xxyy22zz33aabb44"
        plaidInstitutionId:
          type: string
          description: The stable institution ID from Plaid.
          example: "ins_3"
        institutionName:
          type: string
          example: "Chase Bank"
        institutionLogo:
          type: string
          format: uri
          nullable: true
          description: A base64-encoded logo for the institution.
          example: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..."
        syncStatus:
          type: string
          enum: [good, syncing, relink_required, error]
          example: "good"
        lastSuccessfulSync:
          type: string
          format: date-time
          nullable: true
          example: "2025-06-17T20:30:00.000Z"
        lastSyncErrorMessage:
          type: string
          nullable: true
          description: The error message from the last failed sync attempt.
          example: "ITEM_LOGIN_REQUIRED"
        archivedAt:
          type: string
          format: date-time
          nullable: true
          description: Timestamp when the institution was soft-deleted.
          example: "2025-06-18T10:00:00.000Z"

    PlaidItemWithAccounts:
      allOf:
        - $ref: '#/components/schemas/PlaidItem'
        - type: object
          properties:
            accounts:
              type: array
              items:
                $ref: '#/components/schemas/Account'

    Account:
      type: object
      properties:
        id:
          type: string
          description: The unique ID for the Account in our database.
          example: "acct_55pp66oo77ii88uu99"
        plaidAccountId:
          type: string
          description: The unique account ID from Plaid.
          example: "Bxp9pG1mpEtMmKqjK1EGFaVjv4qg74w7eB6lL"
        name:
          type: string
          example: "Primary Checking"
        mask:
          type: string
          example: "0766"
        type:
          type: string
          enum: [depository, credit, loan, investment, other]
          example: "depository"
        subtype:
          type: string
          example: "checking"
        currentBalance:
          type: number
          format: double
          example: 1250.75
        availableBalance:
          type: number
          format: double
          nullable: true
          example: 1200.50
        currencyCode:
          type: string
          example: "USD"
        creditLimit:
          type: number
          format: double
          nullable: true
          description: The credit limit for credit card accounts.
          example: 10000.00

    Transaction:
      type: object
      properties:
        id:
          type: string
          description: The unique ID for the transaction in our database.
          example: "txn_ff66aa77bb88cc99dd"
        plaidTransactionId:
          type: string
          description: The unique transaction ID from Plaid.
          example: "j1KnPo9a3pCpm4k3kG3KcoE5d7R6p7l5dEAZa"
        accountId:
          type: string
          description: The ID of the account this transaction belongs to.
          example: "acct_55pp66oo77ii88uu99"
        amount:
          type: number
          format: double
          example: -12.50
        currencyCode:
          type: string
          example: "USD"
        date:
          type: string
          format: date
          example: "2025-06-15"
        merchantName:
          type: string
          nullable: true
          example: "Starbucks"
        merchantLogo:
          type: string
          format: uri
          nullable: true
          description: The logo of the merchant, if available.
          example: "https://plaid-merchant-logos.plaid.com/starbucks_1060.png"
        primaryCategory:
          type: string
          nullable: true
          example: "Food and Drink"
        detailedCategory:
          type: string
          nullable: true
          example: "Restaurants"
        isPending:
          type: boolean
          example: false
        transactionType:
          type: string
          nullable: true
          description: "Transaction type from Plaid, e.g., 'special', 'place', 'digital'."
        paymentChannel:
          type: string
          nullable: true
          description: "The channel of the transaction, e.g., 'online', 'in store', 'other'."
        notes:
          type: string
          nullable: true
        userCategoryId:
          type: string
          nullable: true

    Pagination:
      type: object
      properties:
        offset:
          type: integer
          example: 0
        limit:
          type: integer
          example: 25
        total:
          type: integer
          example: 542

    ApiError:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              example: "RESOURCE_NOT_FOUND"
            message:
              type: string
              example: "The requested institution with ID 'inst_123' was not found."
            requestId:
              type: string
              description: A unique identifier for the request, useful for debugging and support.
              example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"

  # --- Reusable Parameters ---
  parameters:
    InstitutionId:
      name: institutionId
      in: path
      required: true
      description: The unique identifier of the linked institution.
      schema:
        type: string
        example: "inst_11xxyy22zz33aabb44"

  # --- Reusable Responses ---
  responses:
    BadRequest:
      description: Bad Request. The server could not process the request due to a client error (e.g., malformed syntax, invalid parameters).
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    Unauthorized:
      description: Unauthorized. The request requires authentication, but the provided token was missing or invalid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    Forbidden:
      description: Forbidden. The authenticated user does not have permission to perform this action on the requested resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    NotFound:
      description: Not Found. The requested resource could not be found on the server.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    TooManyRequests:
      description: Rate limit exceeded. The client has sent too many requests in a given amount of time.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    InternalServerError:
      description: Internal Server Error. An unexpected error occurred on the server that prevented it from fulfilling the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'

  # --- Security Schemes ---
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT